general {
	lock_cmd = hyprlock
}

listener {
	timeout = 300
	on-timeout = hyprlock
}

listener {
	timeout = 600
	on-timeout = hyprctl dispatch dpms off
	on-resume = hyprctl dispatch dpms on
}

listener {
	event = lid_close
	on-event = hyprlock
}
