[General]
bld="5i7F50NmFM1eghfYZTdKdQ==|w8ZjTXvc3dwQYNItEWylAZK5XGkG6TY2ndkfVH/n8PyPxBDJau/1KQLJTbYQ"

[Preferences]
AdvancedSettings\systemProxy=false
AdvancedSettings\tun=true
Subscriptions\subsPinnedId=-868981689
TunnelSettings\Muxing\muxingTcpConcurrency=8
TunnelSettings\Muxing\muxingXudpConcurrency=8
TunnelSettings\Noises\noisesPacketRand=10-20
Updates\lastTimeCheckedForUpdate=1775282921
allowConnectionFromLAN\HTTPPort=10809
allowConnectionFromLAN\Socks5Port=10808
fontScale=1.25
graphicsBackend=OpenGL
lastServer=617691262
lastServerName=💎 Авто | Самый быстрый ⚡⚡️⚡️
lastSubscription=-868981689
mode=Dark
screenIndex=0
windowHeight=1112
windowVisibility=2
windowWidth=1894
windowX=13
windowY=74

[Vacancy]
bannerShownCount=2
